
FROM node:22.18.0-alpine3.22

RUN apk --no-cache add sudo
RUN sudo apk --no-cache add python3 make g++
RUN sudo apk --no-cache add bash
WORKDIR /app
COPY ./next /app
RUN npm install
CMD ["npm", "run", "dev"]
