FROM node:22.18.0-alpine3.22

WORKDIR /app

# Install deps first for better cache
COPY ./next/package*.json ./
RUN npm install

# Copy app source
COPY ./next ./

# Copy env separately so it busts cache if updated
COPY ./next/.env ./.env

RUN npm run build

CMD ["npm", "run", "start"]
